# 数据库配置
database:
  driver: mysql
  dsn: "root:lilonghe@tcp(localhost:3306)/restful_go?charset=utf8mb4&parseTime=True&loc=Local"

# JWT配置
jwt:
  secret: asdaajfiaojo
  expiration: 86400  # 24小时，单位：秒

# 服务器配置
server:
  port: 8080
  mode: debug  # 可选：debug, release

# 日志配置
log:
  path: ./logs
  level: debug
  maxSize: 10    # 每个日志文件的最大大小（MB）
  maxBackups: 5  # 保留的旧日志文件数量
  maxAge: 30     # 保留的日志文件的最大天数
  compress: true # 是否压缩旧日志文件