name: Self Hosted Docker

on:
  push:
    branches: ["test-runner"]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, docker]
    defaults:
      run:
        working-directory: ./management-system-react
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker build -t frontend:${{ github.sha }} .
      - name: Deploy
        run: |
          docker stop frontend
          docker run --name frontend:${{ github.sha }} -p 80:80 frontend:latest
